"use server";
import { db } from "@/lib/db";
import { revalidatePath } from "next/cache";

export async function addProduct(f:FormData){const sql=db();const name=String(f.get("name")||"").trim();if(!name)return;await sql`INSERT INTO products(name,category,unit,current_quantity,minimum_quantity,ideal_quantity,expires_at) VALUES(${name},${String(f.get("category")||"Outros")},${String(f.get("unit")||"un")},${Number(f.get("quantity")||0)},${Number(f.get("minimum")||0)},${Number(f.get("ideal")||0)},${f.get("expires")||null}) ON CONFLICT(name) DO NOTHING`;revalidatePath("/")}
export async function setCount(f:FormData){const sql=db();const id=Number(f.get("id")),qty=Math.max(0,Number(f.get("quantity")||0));const rows=await sql`SELECT current_quantity FROM products WHERE id=${id}`;if(!rows[0])return;const old=Number(rows[0].current_quantity);await sql.transaction([sql`INSERT INTO stock_movements(product_id,kind,previous_quantity,new_quantity) VALUES(${id},'count',${old},${qty})`,sql`UPDATE products SET current_quantity=${qty},updated_at=now() WHERE id=${id}`]);revalidatePath("/")}
export async function addEntry(f:FormData){const sql=db();const id=Number(f.get("id")),qty=Math.max(1,Number(f.get("quantity")||1));const exp=f.get("expires")||null;const rows=await sql`SELECT current_quantity FROM products WHERE id=${id}`;if(!rows[0])return;const old=Number(rows[0].current_quantity),next=old+qty;await sql.transaction([sql`INSERT INTO stock_movements(product_id,kind,previous_quantity,new_quantity,expires_at) VALUES(${id},'entry',${old},${next},${exp})`,sql`UPDATE products SET current_quantity=${next},expires_at=COALESCE(${exp},expires_at),updated_at=now() WHERE id=${id}`]);revalidatePath("/")}
export async function generateShoppingList(){const sql=db();const items=await sql`SELECT id,name,GREATEST(ideal_quantity-current_quantity,1) qty FROM products WHERE active AND current_quantity<minimum_quantity ORDER BY name`;if(!items.length)return;const list=await sql`INSERT INTO shopping_lists DEFAULT VALUES RETURNING id`;for(const p of items)await sql`INSERT INTO shopping_list_items(shopping_list_id,product_id,item_name,quantity) VALUES(${list[0].id},${p.id},${p.name},${p.qty})`;revalidatePath("/")}
export async function toggleShoppingItem(f:FormData){const sql=db();await sql`UPDATE shopping_list_items SET checked=NOT checked WHERE id=${Number(f.get("id"))}`;revalidatePath("/")}
