import { db } from "@/lib/db";
import { addEntry,addProduct,generateShoppingList,markStock,setCount,toggleShoppingItem } from "./actions";
import { Box,History,Menu,Plus,Search,ShoppingCart } from "lucide-react";
export const dynamic="force-dynamic";
type P={id:number;name:string;variant:string|null;category:string;unit:string;current_quantity:number;minimum_quantity:number;ideal_quantity:number;stock_status:"ok"|"low"|"out"};
const cats=["Todos","Destilados","Cervejas","Ice / Beats","Refrigerantes","Insumos do bar","Cozinha","Banheiro","Entrada"];
async function load(){try{const sql=db();const [products,moves,items,lots]=await Promise.all([sql`SELECT * FROM products WHERE active ORDER BY category,name,variant NULLS FIRST`,sql`SELECT m.*,p.name,p.variant FROM stock_movements m JOIN products p ON p.id=m.product_id ORDER BY m.created_at DESC LIMIT 30`,sql`SELECT i.* FROM shopping_list_items i JOIN shopping_lists l ON l.id=i.shopping_list_id WHERE l.status='open' AND l.id=(SELECT id FROM shopping_lists WHERE status='open' ORDER BY created_at DESC LIMIT 1) ORDER BY i.checked,i.item_name`,sql`SELECT l.*,p.name,p.variant FROM stock_lots l JOIN products p ON p.id=l.product_id WHERE l.quantity_remaining>0 AND l.expires_at IS NOT NULL ORDER BY l.expires_at LIMIT 20`]);return {products:products as P[],moves,items,lots,error:false}}catch{return {products:[] as P[],moves:[],items:[],lots:[],error:true}}}
export default async function Home({searchParams}:{searchParams:Promise<{tab?:string;q?:string;cat?:string}>}){const s=await searchParams,{tab="estoque",q="",cat="Todos"}=s,d=await load();const filtered=d.products.filter(p=>(cat==="Todos"||p.category===cat)&&(!q||((p.name+" "+(p.variant||"")).toLowerCase().includes(q.toLowerCase()))));const alert=d.products.filter(p=>p.stock_status!=="ok"||p.current_quantity<p.minimum_quantity);const out=alert.filter(p=>p.stock_status==="out"||p.current_quantity===0);const low=alert.filter(p=>p.stock_status!=="out"&&p.current_quantity>0);const title=tab==="comprar"?"Comprar":tab==="entrada"?"Entrada":tab==="historico"?"Histórico":tab==="mais"?"Mais":"Estoque";return <main><header><div><small>CONTROLE DO BAR</small><h1>{title}</h1></div><div className="avatar">B</div></header>{d.error&&<div className="notice">Não foi possível carregar o banco.</div>}
{tab==="estoque"&&<section><div className="summary"><a href="/?tab=comprar"><b>{out.length}</b><span>acabou</span></a><a href="/?tab=comprar"><b>{low.length}</b><span>acabando</span></a></div><form className="search"><Search/><input name="q" defaultValue={q} placeholder="Buscar produto ou sabor..."/></form><div className="chips">{cats.map(c=><a className={cat===c?"selected":""} href={c==="Todos"?"/":"/?cat="+encodeURIComponent(c)} key={c}>{c}</a>)}</div><h2>Produtos</h2><div className="list">{filtered.map(p=><article key={p.id}><div className="row"><div><b>{p.name}</b><small>{p.variant&&<>{p.variant} · </>}{p.category} · {p.unit}</small></div><div className={"qty "+(p.stock_status!=="ok"?"low":"")}>{p.current_quantity}</div></div><form action={setCount} className="inline"><input type="hidden" name="id" value={p.id}/><input name="quantity" type="number" min="0" defaultValue={p.current_quantity}/><button>Atualizar</button></form><form action={markStock} className="quick"><input type="hidden" name="id" value={p.id}/><button name="mark" value="low" className={p.stock_status==="low"?"warn active":""}>Acabando</button><button name="mark" value="out" className={p.stock_status==="out"?"danger active":""}>Acabou</button></form></article>)}{!filtered.length&&!d.error&&<div className="empty">Nenhum produto encontrado.</div>}</div></section>}
{tab==="comprar"&&<section><div className="buySummary"><b>{out.length} acabaram</b><span>{low.length} acabando</span></div>{alert.length>0&&<form action={generateShoppingList}><button className="primary">Gerar / atualizar lista de reposição</button></form>}<h2>Lista atual</h2><div className="list">{d.items.map((x:any)=><form action={toggleShoppingItem} key={x.id}><input type="hidden" name="id" value={x.id}/><button className="shop"><span className="check">{x.checked?"✓":""}</span><span><b>{x.item_name}</b><small>Comprar {x.quantity}</small></span></button></form>)}{!d.items.length&&<div className="empty">Marque itens como acabando/acabou ou deixe o estoque cair abaixo do mínimo.</div>}</div></section>}
{tab==="entrada"&&<section><p className="hint">Registre o que chegou. A validade pertence a esta entrada e é opcional.</p><div className="list">{d.products.map(p=><article key={p.id}><b>{p.name}{p.variant?" · "+p.variant:""}</b><small>Atual: {p.current_quantity} {p.unit}</small><form action={addEntry} className="form"><input type="hidden" name="id" value={p.id}/><div className="inline"><input name="quantity" type="number" min="1" placeholder="Qtd." required/><input name="expires" type="date"/><button>Adicionar</button></div></form></article>)}</div></section>}
{tab==="historico"&&<section><h2>Movimentações</h2><div className="list">{d.moves.map((m:any)=><article key={m.id}><div className="row"><div><b>{m.name}{m.variant?" · "+m.variant:""}</b><small>{m.kind==="entry"?"Entrada":m.kind==="adjustment"?"Acabou":"Contagem"} · {new Date(m.created_at).toLocaleString("pt-BR")}</small></div><strong>{m.previous_quantity} → {m.new_quantity}</strong></div></article>)}</div><h2>Validades registradas</h2><div className="list">{d.lots.map((l:any)=><article key={l.id}><b>{l.name}{l.variant?" · "+l.variant:""}</b><small>{new Date(l.expires_at+"T12:00:00").toLocaleDateString("pt-BR")} · {l.quantity_remaining} un.</small></article>)}</div></section>}
{tab==="mais"&&<section><h2>Novo produto</h2><form action={addProduct} className="card form"><input name="name" placeholder="Nome do produto" required/><input name="variant" placeholder="Variação / sabor (opcional)"/><select name="category" required><option value="">Selecione a categoria</option>{cats.slice(1).map(c=><option key={c}>{c}</option>)}</select><select name="unit" defaultValue="un"><option value="un">Unidade</option><option value="garrafa">Garrafa</option><option value="lata">Lata</option><option value="cx">Caixa</option><option value="pct">Pacote</option><option value="kg">Kg</option></select><div className="two"><label>Estoque mínimo<input name="minimum" type="number" min="0" defaultValue="0"/></label><label>Estoque ideal<input name="ideal" type="number" min="0" defaultValue="0"/></label></div><label>Quantidade inicial <small>(opcional)</small><input name="quantity" type="number" min="0" defaultValue="0"/></label><button className="primary">Cadastrar produto</button></form><div className="menuCard"><b>Categorias usadas</b><small>{cats.slice(1).join(" · ")}</small></div></section>}
<nav><N href="/" on={tab==="estoque"} icon={<Box/>} label="Estoque"/><N href="/?tab=comprar" on={tab==="comprar"} icon={<ShoppingCart/>} label="Comprar"/><N href="/?tab=entrada" on={tab==="entrada"} icon={<Plus/>} label="Entrada"/><N href="/?tab=historico" on={tab==="historico"} icon={<History/>} label="Histórico"/><N href="/?tab=mais" on={tab==="mais"} icon={<Menu/>} label="Mais"/></nav></main>}
function N({href,on,icon,label}:any){return <a href={href} className={on?"active":""}>{icon}<span>{label}</span></a>}
