import { db } from "@/lib/db";
import { addEntry,addProduct,generateShoppingList,setCount,toggleShoppingItem } from "./actions";
import { Box,History,Menu,Plus,ShoppingCart } from "lucide-react";
export const dynamic="force-dynamic";
type P={id:number;name:string;category:string;unit:string;current_quantity:number;minimum_quantity:number;ideal_quantity:number;expires_at:string|null};
async function load(){try{const sql=db();const [products,moves,items]=await Promise.all([sql`SELECT * FROM products WHERE active ORDER BY category,name`,sql`SELECT m.*,p.name FROM stock_movements m JOIN products p ON p.id=m.product_id ORDER BY m.created_at DESC LIMIT 30`,sql`SELECT i.* FROM shopping_list_items i JOIN shopping_lists l ON l.id=i.shopping_list_id WHERE l.status='open' AND l.id=(SELECT id FROM shopping_lists WHERE status='open' ORDER BY created_at DESC LIMIT 1) ORDER BY i.checked,i.item_name`]);return {products:products as P[],moves,items,error:false}}catch{return {products:[] as P[],moves:[],items:[],error:true}}}
export default async function Home({searchParams}:{searchParams:Promise<{tab?:string}>}){const {tab="estoque"}=await searchParams;const d=await load();const low=d.products.filter(p=>p.current_quantity<p.minimum_quantity);const soon=d.products.filter(p=>p.expires_at&&new Date(p.expires_at).getTime()-Date.now()<30*86400000);const title=tab==="comprar"?"Comprar":tab==="entrada"?"Entrada":tab==="historico"?"Histórico":tab==="mais"?"Mais":"Estoque";return <main><header><div><small>CONTROLE DO BAR</small><h1>{title}</h1></div><div className="avatar">B</div></header>{d.error&&<div className="notice">Banco ainda não conectado. Assim que o Neon estiver configurado, os dados aparecem aqui.</div>}
{tab==="estoque"&&<section><div className="summary"><a href="/?tab=comprar"><b>{low.length}</b><span>estoque baixo</span></a><div><b>{soon.length}</b><span>validade próxima</span></div></div><h2>Produtos</h2><div className="list">{d.products.map(p=><article key={p.id}><div className="row"><div><b>{p.name}</b><small>{p.category} · {p.unit}</small></div><strong className={p.current_quantity<p.minimum_quantity?"low":""}>{p.current_quantity}</strong></div><form action={setCount} className="inline"><input type="hidden" name="id" value={p.id}/><input name="quantity" type="number" min="0" defaultValue={p.current_quantity}/><button>Atualizar</button></form></article>)}{!d.products.length&&!d.error&&<div className="empty">Cadastre o primeiro produto em Mais.</div>}</div></section>}
{tab==="comprar"&&<section>{low.length>0&&<form action={generateShoppingList}><button className="primary">Gerar lista do que falta</button></form>}<h2>Lista atual</h2><div className="list">{d.items.map((x:any)=><form action={toggleShoppingItem} key={x.id}><input type="hidden" name="id" value={x.id}/><button className="shop"><span className="check">{x.checked?"✓":""}</span><span><b>{x.item_name}</b><small>Comprar {x.quantity}</small></span></button></form>)}{!d.items.length&&<div className="empty">A lista gerada aparecerá aqui.</div>}</div></section>}
{tab==="entrada"&&<section><p>Chegou mercadoria? Some ao estoque e informe a validade.</p><div className="list">{d.products.map(p=><article key={p.id}><b>{p.name}</b><small>Atual: {p.current_quantity} {p.unit}</small><form action={addEntry} className="form"><input type="hidden" name="id" value={p.id}/><div className="inline"><input name="quantity" type="number" min="1" placeholder="Qtd." required/><input name="expires" type="date"/><button>Adicionar</button></div></form></article>)}</div></section>}
{tab==="historico"&&<section><div className="list">{d.moves.map((m:any)=><article key={m.id}><div className="row"><div><b>{m.name}</b><small>{m.kind==="entry"?"Entrada":"Contagem"} · {new Date(m.created_at).toLocaleString("pt-BR")}</small></div><strong>{m.previous_quantity} → {m.new_quantity}</strong></div></article>)}{!d.moves.length&&<div className="empty">As movimentações aparecerão aqui.</div>}</div></section>}
{tab==="mais"&&<section><h2>Novo produto</h2><form action={addProduct} className="card form"><input name="name" placeholder="Nome do produto" required/><input name="category" placeholder="Categoria"/><input name="unit" placeholder="Unidade (un, cx, garrafa...)"/><input name="quantity" type="number" min="0" placeholder="Quantidade atual"/><input name="minimum" type="number" min="0" placeholder="Estoque mínimo"/><input name="ideal" type="number" min="0" placeholder="Estoque ideal"/><input name="expires" type="date"/><button className="primary">Cadastrar produto</button></form></section>}
<nav><N href="/" on={tab==="estoque"} icon={<Box/>} label="Estoque"/><N href="/?tab=comprar" on={tab==="comprar"} icon={<ShoppingCart/>} label="Comprar"/><N href="/?tab=entrada" on={tab==="entrada"} icon={<Plus/>} label="Entrada"/><N href="/?tab=historico" on={tab==="historico"} icon={<History/>} label="Histórico"/><N href="/?tab=mais" on={tab==="mais"} icon={<Menu/>} label="Mais"/></nav></main>}
function N({href,on,icon,label}:any){return <a href={href} className={on?"active":""}>{icon}<span>{label}</span></a>}
